First (simplest) attempt at parallax.
rivasvict/wedding-app pull request #42
Opened 2017-07-21 21:53 UTC by jobliz

First attempt at solving #17. More images can be added / the image could be changed.

2017-07-22 13:45 UTC, rivasvict requested changes
@jobliz please review the comment. Thanks.

2017-07-22 13:45 UTC, vctr90 commented on package.json
> +    "parallax-js": "git+https://github.com/wagerfield/parallax.git",
@jobliz Do we need this here?

2017-07-24 14:43 UTC, jobliz commented
"parallax-js" was a leftover from tests that can be erased. I tried uninstalling npm-run-all, but then npm run serve-dev didn't run. I think the line was modified (extra space) when I added parallax-js and thus went into the changes. So, npm-run-all seems to be necessary.

2017-07-24 22:07 UTC, rivasvict requested changes
@jobliz please take a look at the comments, Just those ones, other than that it looks good

2017-07-24 22:07 UTC, rivasvict commented on src/client/app/landing.html
> +      $(document).ready(function() {
@jobliz Can you please move this logic inside a file propertly requested by webpack. Please make use of the fact that this page gets initialized here: https://github.com/vctr90/wedding-app/blob/development/src/client/app/mainAppLoader.js#L31 so you do not need the ready jquery function.

2017-07-25 01:14 UTC, rivasvict approved these changes
@jobliz Thanks!! what a great Job *.* I loved it!!

2017-07-25 02:05 UTC, merged