Character counter for comment textarea implemented.
rivasvict/wedding-app pull request #52
Opened 2017-07-30 00:47 UTC by jobliz

Pull request for issue #48

2017-07-30 00:54 UTC, jobliz commented
Last commit solves a slight problem that placed confirmation data on all .modal-body divs.

2017-07-31 01:24 UTC, rivasvict requested changes
@jobliz just those little comments, functionality is great, other then that, just little things. Thanks!!
Amazing Job!

2017-07-31 01:24 UTC, vctr90 commented on src/client/app/modules/markupControllers/comment.js
> +      this.$target.on("change paste keyup", () => {
Can you please  separate this callback into a another defined function?

2017-07-31 01:24 UTC, vctr90 commented on src/client/app/modules/markupControllers/comment.js
> +        const newContentStringLength = newContentString.length;
This can be broken into a getter `getNewContentStringLength()`

2017-07-31 01:24 UTC, vctr90 commented on src/client/app/modules/markupControllers/comment.js
> +        this.$target.val(this.$target.val().substr(0, this.characterLimit));
Please separate this into a function that describes the comment you placed above.

2017-07-31 01:24 UTC, vctr90 commented on src/client/app/modules/markupControllers/comment.js
> +        console.log("Counter a " + newContentStringLength);
Ooops, can you please get rid of this?

2017-07-31 01:24 UTC, vctr90 commented on src/client/app/modules/markupControllers/comment.js
> +        this.$counter.html(newContentStringLength + " de " +
This can be another function like `setCounterTextBasedOnCharactersCount()`

2017-07-31 01:24 UTC, vctr90 commented on src/client/app/modules/markupControllers/comment.js
> +        if(newContentStringLength > (this.characterLimit - 20)) {
This if-else statement can be also broken into another function called `handleCounterClass()`

2017-08-06 03:16 UTC, rivasvict approved these changes
@jobliz great Job. Thanks. Please merge

2017-08-07 00:12 UTC, merged